# Changes here will be overwritten by Copier
_commit: v0.0.7-16-g31112c5
_src_path: gh:LabAutomationAndScreening/copier-base-template.git
description: Managing Central Infrastructure of an AWS Organization
python_ci_versions:
- 3.13.2
python_version: 3.13.2
repo_name: copier-aws-central-infrastructure
repo_org_name: LabAutomationAndScreening
ssh_port_number: 58573
template_uses_pulumi: true
template_uses_python: true

