[project]
name = "copier-aws-central-infrastructure"
version = "0.1.0"
description = "Managing Central Infrastructure of an AWS Organization"
readme = "README.md"
requires-python = ">=3.13.2"
dependencies = [
    # Managed by upstream template
    "pytest>=8.4.2",
    "pytest-cov>=7.0.0",
    "pytest-randomly>=4.0.1",
    "pyright[nodejs]>=1.1.407",
    "copier>=9.10.3",
    "copier-template-extensions>=0.3.3"

    # Specific to this template


]
